In [7]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:

!wget -O down.zip "https://storage.googleapis.com/kaggle-data-sets/492658/931985/compressed/rapids.0.12.0.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220411T153459Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=5c55c8951a3b0f62c31a7b050e62283aa54f47e72aa63a14d63927ab00160d047806060ab3cc2af763558e62bf094fbbceff330347328162417672bea3a2da5cb8d368691b37cf841f4ac366bd18e905e6970d46e22a9057452b67dac34604963b900c163c36aa8b0f755f1f5fdf1541473f2f916cd41088e97de81b00557b17c7f28a5228d2de4626823cd24a84dcff81957168a26f8092cd720878e235933e9d72d1f72d0921e9c8257caf664049c8a1424d2c85995a7afe6a992d2bb69fa4e40881eed010a9e14db0bb802f951f61aa5adb7deff8540502f6f6850c3eafb349f02b95562aa1cf099f7a5a279434ecd780df96295d3721abcb15d3d48883db"
!unzip ./down.zip
!rm ./down.zip


        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

IndentationError: expected an indented block (2103777692.py, line 15)

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

from sklearn.metrics import mean_squared_error 

import random

In [9]:
df= pd.read_csv('../input/cascsv/cas.csv')
df.head()

Unnamed: 0  bicycle  bridge  bus  carStationWagon  cliffBank  \
0           0      0.0     0.0  0.0              1.0        0.0   
1           1      0.0     0.0  0.0              3.0        0.0   
2           2      0.0     0.0  0.0              1.0        1.0   
3           3      0.0     0.0  0.0              1.0        1.0   
4           4      0.0     0.0  0.0              2.0        0.0   

   crashFinancialYear  debris  ditch  fence  ...  suv  taxi  trafficSign  \
0                   1     0.0    0.0    0.0  ...  0.0   0.0          0.0   
1                  12     0.0    0.0    0.0  ...  0.0   0.0          0.0   
2                   7     0.0    0.0    0.0  ...  0.0   0.0          0.0   
3                   7     0.0    0.0    0.0  ...  0.0   0.0          0.0   
4                   4     0.0    0.0    0.0  ...  0.0   0.0          0.0   

   trafficControl  train  tree  truck  urban  vehicle  injury  
0               0    0.0   0.0    0.0      1      0.0       0  
1               7    0.0   0.0    0.0      1      0.0       0  
2               2    0.0   0.0    0.0      0      0.0       0  
3               2    0.0   0.0    0.0      0      0.0       0  
4               0    0.0   0.0    0.0      1      0.0       0  

[5 rows x 38 columns]

In [10]:
df.drop(['Unnamed: 0'], inplace=True, axis=1)

In [11]:
df.shape

(758006, 37)

In [12]:
x = df.iloc[:,:-1]
x.shape

(758006, 36)

In [13]:
y = df.iloc[:, -1:]
y.shape

(758006, 1)

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)

In [15]:
!wget -O down.zip "https://storage.googleapis.com/kaggle-data-sets/492658/931985/compressed/rapids.0.12.0.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220411T153459Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=5c55c8951a3b0f62c31a7b050e62283aa54f47e72aa63a14d63927ab00160d047806060ab3cc2af763558e62bf094fbbceff330347328162417672bea3a2da5cb8d368691b37cf841f4ac366bd18e905e6970d46e22a9057452b67dac34604963b900c163c36aa8b0f755f1f5fdf1541473f2f916cd41088e97de81b00557b17c7f28a5228d2de4626823cd24a84dcff81957168a26f8092cd720878e235933e9d72d1f72d0921e9c8257caf664049c8a1424d2c85995a7afe6a992d2bb69fa4e40881eed010a9e14db0bb802f951f61aa5adb7deff8540502f6f6850c3eafb349f02b95562aa1cf099f7a5a279434ecd780df96295d3721abcb15d3d48883db"
!unzip ./down.zip
!rm ./down.zip

--2022-04-12 09:39:21--  https://storage.googleapis.com/kaggle-data-sets/492658/931985/compressed/rapids.0.12.0.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220411T153459Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=5c55c8951a3b0f62c31a7b050e62283aa54f47e72aa63a14d63927ab00160d047806060ab3cc2af763558e62bf094fbbceff330347328162417672bea3a2da5cb8d368691b37cf841f4ac366bd18e905e6970d46e22a9057452b67dac34604963b900c163c36aa8b0f755f1f5fdf1541473f2f916cd41088e97de81b00557b17c7f28a5228d2de4626823cd24a84dcff81957168a26f8092cd720878e235933e9d72d1f72d0921e9c8257caf664049c8a1424d2c85995a7afe6a992d2bb69fa4e40881eed010a9e14db0bb802f951f61aa5adb7deff8540502f6f6850c3eafb349f02b95562aa1cf099f7a5a279434ecd780df96295d3721abcb15d3d48883db
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.107.128, 172.253.123.128, 142.250.98.128, ...
Connecting 

In [16]:
%%capture
import sys
!cp ../rapids.0.12.0 /opt/conda/envs/rapids.tar.gz
!cd /opt/conda/envs/ && tar -xzvf rapids.tar.gz
sys.path = ["/opt/conda/envs/rapids/lib"] + ["/opt/conda/envs/rapids/lib/python3.6"] + ["/opt/conda/envs/rapids/lib/python3.6/site-packages"] + sys.path
!cp /opt/conda/envs/rapids/lib/libxgboost.so /opt/conda/lib/


In [17]:
import cudf
from cuml.svm import SVC

In [18]:
X_train = cudf.DataFrame.from_pandas(x_train)
X_test = cudf.DataFrame.from_pandas(x_test)
Y_train = y_train
Y_test = y_test

In [19]:
model = SVC(C=10, kernel='linear')

In [20]:
%%time

model.fit(X_train, Y_train)

CPU times: user 38min 59s, sys: 3.51 s, total: 39min 2s
Wall time: 39min 8s


SVC()

In [21]:
y_pred= model.predict(X_test).to_pandas().values

In [22]:
from sklearn import metrics

In [23]:
print(metrics.classification_report(Y_test,y_pred))
print(metrics.confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.98      0.84     53173
           1       0.76      0.18      0.29     22628

    accuracy                           0.74     75801
   macro avg       0.75      0.58      0.57     75801
weighted avg       0.74      0.74      0.68     75801

[[51852  1321]
 [18535  4093]]


In [24]:
pd.DataFrame(y_test).value_counts()

injury
0         53173
1         22628
dtype: int64

In [25]:
model = SVC(C=10,kernel='rbf')

In [26]:
%%time

model.fit(X_train, Y_train)

y_pred= model.predict(X_test).to_pandas().values

print(metrics.classification_report(Y_test,y_pred))
print(metrics.confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.98      0.84     53173
           1       0.76      0.18      0.29     22628

    accuracy                           0.74     75801
   macro avg       0.75      0.58      0.57     75801
weighted avg       0.74      0.74      0.68     75801

[[51872  1301]
 [18546  4082]]
CPU times: user 11min 13s, sys: 1.36 s, total: 11min 14s
Wall time: 11min 14s


In [27]:
model = SVC(C=10,kernel='poly')

In [28]:
%%time

model.fit(X_train, Y_train)

y_pred= model.predict(X_test).to_pandas().values

print(metrics.classification_report(Y_test,y_pred))
print(metrics.confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.98      0.84     53173
           1       0.77      0.16      0.27     22628

    accuracy                           0.74     75801
   macro avg       0.75      0.57      0.55     75801
weighted avg       0.74      0.74      0.67     75801

[[52084  1089]
 [18965  3663]]
CPU times: user 7min 56s, sys: 1 s, total: 7min 57s
Wall time: 7min 57s


In [29]:
model = SVC(C=10,kernel='sigmoid')

In [30]:
%%time

model.fit(X_train, Y_train)

y_pred= model.predict(X_test).to_pandas().values

print(metrics.classification_report(Y_test,y_pred))
print(metrics.confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.70      0.70      0.70     53173
           1       0.29      0.28      0.29     22628

    accuracy                           0.58     75801
   macro avg       0.49      0.49      0.49     75801
weighted avg       0.58      0.58      0.58     75801

[[37343 15830]
 [16218  6410]]
CPU times: user 41.7 s, sys: 171 ms, total: 41.9 s
Wall time: 41.9 s


In [31]:
from cuml.ensemble import RandomForestClassifier as cuRFC


cuml_model = cuRFC(max_features=1.0,
                   n_bins=8,
                   n_estimators=40)
cuml_model.fit(X_train,Y_train)
y_pred = cuml_model.predict(X_test)

y_pred= model.predict(X_test).to_pandas().values
#print("Predicted labels : ", y_pred)

/opt/conda/lib/python3.7/site-packages/cuml/internals/api_decorators.py:567: UserWarning: To use pickling or GPU-based prediction first train using float32 data to fit the estimator
  ret_val = func(*args, **kwargs)
/opt/conda/lib/python3.7/site-packages/cuml/internals/api_decorators.py:586: UserWarning: GPU based predict only accepts np.float32 data. The model was trained on np.float64 data hence cannot use GPU-based prediction! 
Defaulting to CPU-based Prediction. 
To predict on float-64 data, set parameter predict_model = 'CPU'
  ret_val = func(*args, **kwargs)


In [32]:
print(metrics.classification_report(Y_test,y_pred))
print(metrics.confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.70      0.70      0.70     53173
           1       0.29      0.28      0.29     22628

    accuracy                           0.58     75801
   macro avg       0.49      0.49      0.49     75801
weighted avg       0.58      0.58      0.58     75801

[[37343 15830]
 [16218  6410]]
